package com.test.project.entity;
// Generated 2018-2-28 9:16:57 by Hibernate Tools 5.2.8.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HelloUser generated by hbm2java
 */
@Entity
@Table(name = "hello_user", catalog = "hello")
public class HelloUser implements java.io.Serializable {

	private static final long serialVersionUID = -8546990949533067155L;
	private Integer userId;
	private String userName;
	private Integer userAge;
	private String ere;
	private String enm;

	public HelloUser() {
	}

	public HelloUser(String userName, Integer userAge, String ere, String enm) {
		this.userName = userName;
		this.userAge = userAge;
		this.ere = ere;
		this.enm = enm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "user_name", length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_age")
	public Integer getUserAge() {
		return this.userAge;
	}

	public void setUserAge(Integer userAge) {
		this.userAge = userAge;
	}

	@Column(name = "ere", length = 8)
	public String getEre() {
		return this.ere;
	}

	public void setEre(String ere) {
		this.ere = ere;
	}

	@Column(name = "enm", length = 2)
	public String getEnm() {
		return this.enm;
	}

	public void setEnm(String enm) {
		this.enm = enm;
	}

}
