package com.test.project.entity;
// Generated 2018-2-28 9:16:57 by Hibernate Tools 5.2.8.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "hello")
public class Product implements java.io.Serializable {

	private Integer id;
	private String proName;
	private String proLevel;
	private BigDecimal proPrice;
	private String proDescribe;

	public Product() {
	}

	public Product(String proName, String proLevel, BigDecimal proPrice,
			String proDescribe) {
		this.proName = proName;
		this.proLevel = proLevel;
		this.proPrice = proPrice;
		this.proDescribe = proDescribe;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "pro_name")
	public String getProName() {
		return this.proName;
	}

	public void setProName(String proName) {
		this.proName = proName;
	}

	@Column(name = "pro_level")
	public String getProLevel() {
		return this.proLevel;
	}

	public void setProLevel(String proLevel) {
		this.proLevel = proLevel;
	}

	@Column(name = "pro_price", precision = 20, scale = 0)
	public BigDecimal getProPrice() {
		return this.proPrice;
	}

	public void setProPrice(BigDecimal proPrice) {
		this.proPrice = proPrice;
	}

	@Column(name = "pro_describe")
	public String getProDescribe() {
		return this.proDescribe;
	}

	public void setProDescribe(String proDescribe) {
		this.proDescribe = proDescribe;
	}

}
