package com.test.project.entity;
// Generated 2018-2-28 9:21:38 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbNook generated by hbm2java
 */
@Entity
@Table(name = "tb_nook", catalog = "hello")
public class TbNook implements java.io.Serializable {

	private Integer id;
	private String info;

	public TbNook() {
	}

	public TbNook(String info) {
		this.info = info;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "info", length = 100)
	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

}
