package com.test.project.entity;
// Generated 2018-2-28 9:16:57 by Hibernate Tools 5.2.8.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.junit.Test;

/**
 * TbTest generated by hbm2java
 */
@Entity
@Table(name = "tb_test", catalog = "hello")
public class TbTest implements java.io.Serializable {

	private static final long serialVersionUID = -3541080698812432358L;
	private Integer id;
	private String name;
	private String enm;
	private String list;

	public TbTest() {
	}

	public TbTest(String name, String enm, String list) {
		this.name = name;
		this.enm = enm;
		this.list = list;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "enm", length = 6)
	public String getEnm() {
		return this.enm;
	}

	public void setEnm(String enm) {
		this.enm = enm;
	}

	@Column(name = "list", length = 11)
	public String getList() {
		return this.list;
	}

	public void setList(String list) {
		this.list = list;
	}

	@Test
	private void test() {

	}

}
