package com.test.project.entity;
// Generated 2018-2-28 9:16:57 by Hibernate Tools 5.2.8.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

/**
 * TestPerson generated by hbm2java
 */
@Entity
@Table(name = "test_person", catalog = "hello")
public class TestPerson implements java.io.Serializable {

	private static final long serialVersionUID = 8012176413411258121L;
	private Integer personId;
	private String personName;
	private Integer personAge;
	private String personSex;
	private String personDescrib;

	public TestPerson() {
	}

	public TestPerson(String personName, Integer personAge, String personSex,
			String personDescrib) {
		this.personName = personName;
		this.personAge = personAge;
		this.personSex = personSex;
		this.personDescrib = personDescrib;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "person_id", unique = true, nullable = false)
	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	@Column(name = "person_name", length = 50)
	public String getPersonName() {
		return this.personName;
	}

	public void setPersonName(String personName) {
		this.personName = personName;
	}

	@Column(name = "person_age")
	public Integer getPersonAge() {
		return this.personAge;
	}

	public void setPersonAge(Integer personAge) {
		this.personAge = personAge;
	}

	@Column(name = "person_sex", length = 50)
	public String getPersonSex() {
		return this.personSex;
	}

	public void setPersonSex(String personSex) {
		this.personSex = personSex;
	}

	@Column(name = "person_describ", length = 200)
	public String getPersonDescrib() {
		return this.personDescrib;
	}

	public void setPersonDescrib(String personDescrib) {
		this.personDescrib = personDescrib;
	}

	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
	}

}
