package com.test.project.entity;
// Generated 2018-2-28 9:16:57 by Hibernate Tools 5.2.8.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * TTeacher generated by hbm2java
 */
@Entity
@Table(name = "t_teacher", catalog = "hello")
public class TTeacher implements java.io.Serializable {

	private static final long serialVersionUID = -8427389327767865869L;
	private Integer id;
	private String name;
	private String age;
	private String sex;
	private Date createDate;

	public TTeacher() {
	}

	public TTeacher(String name, String age, String sex, Date createDate) {
		this.name = name;
		this.age = age;
		this.sex = sex;
		this.createDate = (Date) createDate.clone();
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "age", length = 30)
	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	@Column(name = "sex", length = 30)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	// @Temporal(TemporalType.TIME)
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return (Date) this.createDate.clone();
	}

	public void setCreateDate(Date createDate) {
		this.createDate = (Date) createDate.clone();
	}

	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
	}

}
